android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false

# Memoria controlada para evitar OOM en CI
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m

# Deshabilitar daemon y paralelismo (evita conflictos en CI)
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.caching=false

# FIX: evita "Already watching path" en GitHub Actions
org.gradle.vfs.watch=false
android.experimental.enableNewResourceShrinker=false
